resources:
  - name: config-server
    type: git
    check_every: 10s
    source:
      uri: https://github.com/github-sree/config-server.git
      branch: dev

jobs:
  - name: build and test
    public: true
    plan:
      - get: config-server
        trigger: true
      - task: build
        file: config-server/tasks/build.yml