resources:
  - name: config-server
    type: git
    check_every: 10s
    source:
      uri: https://github.com/github-sree/config-server.git
      branch: main

jobs:
  - name: build
    public: true
    plan:
      - get: config-server
        trigger: true
      - task: Build project
        file: config-server/concourse/tasks/build.yml
      - task: Deploy artifact
        file: config-server/concourse/tasks/deploy.yml